// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetDiary.Data;

#nullable disable

namespace VetDiary.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210210110_SeedSpeciesAndBreed")]
    partial class SeedSpeciesAndBreed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VetDiary.Data.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mixed Breed",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Labrador Retriever",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "German Shepherd",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Golden Retriever",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "French Bulldog",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cavalier King Charles Spaniel",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poodle",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jack Russell Terrier",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Corgi",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rottweiler",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Yorkshire Terrier",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Boxer",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Dachshund",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Beagle",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Siberian Husky",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Doberman Pinscher",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Shih Tzu",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Chihuahua",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pomeranian",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Border Collie",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cocker Spaniel",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Australian Shepherd",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Great Dane",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Maltese",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Boston Terrier",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "Cane Corso",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Akita",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 28,
                            Name = "Saint Bernard",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Bernese Mountain Dog",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Other / Unknown",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "Domestic Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 32,
                            Name = "Domestic Longhair",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 33,
                            Name = "Maine Coon",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 34,
                            Name = "Persian",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 35,
                            Name = "Siamese",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 36,
                            Name = "Ragdoll",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 37,
                            Name = "British Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 38,
                            Name = "Siberian",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 39,
                            Name = "Norwegian Forest Cat",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 40,
                            Name = "Birman",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 41,
                            Name = "Bengal",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 42,
                            Name = "Abyssinian",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 43,
                            Name = "Scottish Fold",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 44,
                            Name = "Sphynx",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 45,
                            Name = "Burmese",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 46,
                            Name = "Russian Blue",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 47,
                            Name = "American Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 48,
                            Name = "Oriental Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 49,
                            Name = "Devon Rex",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 50,
                            Name = "Mixed Breed",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 51,
                            Name = "Other / Unknown",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 52,
                            Name = "Arabian",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 53,
                            Name = "Andalusian",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 54,
                            Name = "American Quarter Horse",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 55,
                            Name = "Friesian",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 56,
                            Name = "Thoroughbred",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 57,
                            Name = "Appaloosa",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 58,
                            Name = "Morgan",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 59,
                            Name = "Clydesdale",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 60,
                            Name = "Shire",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 61,
                            Name = "Orlov Trotter",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 62,
                            Name = "Hackney",
                            SpeciesId = 13
                        });
                });

            modelBuilder.Entity("VetDiary.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("VetDiary.Data.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Behaviour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BodyConditionScore")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitReasonId")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VisitReasonId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("bit");

                    b.Property<int?>("MicrochipNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rabbit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hamster"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Guinea Pig"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Parrot"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ferret"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canary"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Turtle"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Snake"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lizard"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Snake"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Horse"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Donkey"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sheep"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Goat"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pony"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pig"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Chinchilla"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Other Mammal"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Other Bird"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Other Reptile"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Other Exotic"
                        });
                });

            modelBuilder.Entity("VetDiary.Data.Models.VisitReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VisitReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Checkup"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Illness"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vaccination"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Injury"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dental Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Parasite Treatment"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Emergency"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Follow Up"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetDiary.Data.Models.Breed", b =>
                {
                    b.HasOne("VetDiary.Data.Models.Species", "Species")
                        .WithMany("Breeds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("VetDiary.Data.Models.DiaryEntry", b =>
                {
                    b.HasOne("VetDiary.Data.Models.Pet", "Pet")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetDiary.Data.Models.VisitReason", "VisitReason")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("VisitReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("VisitReason");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Pet", b =>
                {
                    b.HasOne("VetDiary.Data.Models.Breed", "Breed")
                        .WithMany("Pets")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VetDiary.Data.Models.Client", "Client")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetDiary.Data.Models.Species", "Species")
                        .WithMany("Pets")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Client");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Breed", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Client", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Pet", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("VetDiary.Data.Models.Species", b =>
                {
                    b.Navigation("Breeds");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetDiary.Data.Models.VisitReason", b =>
                {
                    b.Navigation("DiaryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
