<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VetDiary.Services\VetDiary.Services.csproj" />
    <ProjectReference Include="..\VetDiary.Data\VetDiary.Data.csproj" />
    <ProjectReference Include="..\VetDiary.Data.Models\VetDiary.Data.Models.csproj" />
    <ProjectReference Include="..\VetDiary.ViewModels\VetDiary.ViewModels.csproj" />
    <ProjectReference Include="..\VetDiary.Shared\VetDiary.Shared.csproj" />
  </ItemGroup>

</Project>